spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/findmypet?useUnicode=yes&characterEncoding=UTF-8&connectTimeout=2000&autoReconnect=true&serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
  data:
    mongodb:
      uri: mongodb://root:1234@localhost:27017/post?authSource=admin
    redis:
      port: 6379
      host: localhost
      password: healthgood1!
auth:
  grant-type: authorization_code
  kakao:
    client-id: asasas
  google:
    client-id: asasas
    client-secret: sasas

consume:
  kafka:
    bootstrap:
      server: localhost:9092

server:
  port: 8081

platform-holder:
  application:
    id: test
  cdn:
    domain: http://localhost:8080
